### ISSUE TITLE
I want to join the organization.

### ISSUE THREAD

**Issue by Shukla007** [Py-Contributors/Getting-Started#10]
I would like to join this organization and contribute to the community and learn new things.

**Comment by codeperfectplus** [comment]
PLease create an issue on this repo. you will get an invite. 

https://github.com/Py-Contributors/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invite.yaml&title=Please+invite+me+to+the+GitHub+Community+Organization

welcome to the Py-contributors community.

**Comment by Chandra-Sekhar-Bala** [comment]
I hope your question has been answered @Shukla007, please inform so that we can close this issue.

**Comment by Shukla007** [comment]
yes the question has been answered thank you
