### ISSUE TITLE
Interested to join Py-contributors.

### ISSUE THREAD

**Issue by DrakeEntity** [Py-Contributors/Getting-Started#4]
#### Py-contributors is open-source community for 

- Python
- Machine learning
- Deep learning
- Data Science

If you are interested in any of these then you are welcome to the community. 

Join community on Discord Channel - https://discord.gg/FXyh2S3

**Comment by shrey27tri01** [comment]
HI! I am a Python programmer, and my Github username is @shrey27tri01 .

**Comment by nithinkodadhavadee** [comment]
I am Nithin and recently stumbled into the world of AI. I did a few courses on Machine Learning and started Deep learning like a month ago. I still am a noob in the whole area. My Github username is @[nithinkodadhavadee](https://github.com/nithinkodadhavadee).
